server:
  port: 5000

spring:
  application:
    name: notification-service

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.notification: DEBUG
